
server:
  port: 8081

spring:
  datasource:
    name: blog
    url: jdbc:mysql://127.0.0.1:3306/blog
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:static
  thymeleaf:
    prefix: classpath:/static/


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: org.yorha.blog.Entity

